using multi threads to check for outdated
Signed-off-by: Tin Lai <oscar@tinyiu.com>

diff --git a/libexec/shsh-outdated b/libexec/shsh-outdated
--- a/libexec/shsh-outdated
+++ b/libexec/shsh-outdated
@@ -1,19 +1,56 @@
 #!/usr/bin/env sh
 #
 # Summary: Displays a list of outdated packages
-# Usage: shsh outdated
+# Usage: shsh outdated [-q|--quiet]
 
 set -e
 
-for package in $(shsh list); do
-  package_path="$SHSH_PACKAGES_PATH/$package"
-  if [ ! -L "$package_path" ]; then
-    cd $package_path
+case "$1" in
+  -q|--quiet)
+    quiet="true"
+    ;;
+esac
+
+check_up_to_date() {
+  # check updates with git, where directory is $1
+  dir="$SHSH_PACKAGES_PATH/$1"
+  # quiet="$2"
+  if [ ! -L "$dir" ]; then
+    cd "$dir"
     git remote update > /dev/null 2>&1
     if git symbolic-ref --short -q HEAD > /dev/null; then
-        if [ "$(git rev-list --count HEAD...HEAD@{upstream})" -gt 0 ]; then
-          echo "$package"
-        fi
+      if [ "$(git rev-list --count HEAD...HEAD@{upstream})" -gt 0 ]; then
+        echo "$1"
+      else
+        [ -z "$quiet" ] && echo "Up-to-date with $1" || :
+      fi
     fi
   fi
-done
+}
+
+
+if command -v mktemp >/dev/null && command -v flock >/dev/null; then
+  # perform checks with multithreads
+  lockfile="$(mktemp)"
+  for package in $(shsh list); do
+    (
+      output=$(check_up_to_date "$package")
+      # try to obtains lock to output to stdout, with max timeout 20 sec
+      if [ -n "$output" ]; then
+        flock -w 20 5 || :
+        echo "$output"
+      fi
+    ) 5>"$lockfile" &
+  done
+  wait
+  # cleanup
+  rm -f "$lockfile"
+else
+  # doesn't contain the necessary utilities, we will perform in sequential order
+  for package in $(shsh list); do
+    output=$(check_up_to_date "$package")
+    if [ -n "$output" ]; then
+      echo "$output"
+    fi
+  done
+fi
