implements retrieving recipe from github
Signed-off-by: Tin Lai <oscar@tinyiu.com>

diff --git a/libexec/shsh-install b/libexec/shsh-install
--- a/libexec/shsh-install
+++ b/libexec/shsh-install
@@ -13,6 +13,8 @@
 #       -h, --hook <HOOK_TYPE>[=<CONTENT>]
 #                    add HOOK to this package, which is triggered while
 #                    installing or upgrading a package
+#       -r, --recipe interpret the given package name as a hosted recipt at
+#                    github.com/soraxas/shsh-recipes.
 #       -v --variable <VAR>=<VAL>
 #                    set a variable VAR with value VAL,
 #                    useful for setting up files for linking
@@ -111,6 +113,9 @@ if [ "$#" != 0 ]; then
         # set -- "PLACE/HOLDER" "$@"
         plain_package="true"
         ;;
+      -r|--recipe)
+        as_recipe="true"
+        ;;
       --*=*)  # convert '--name=arg' to '--name' 'arg'
         set -- "${opt%%=*}" "${opt#*=}" "$@";;
       -[!-]?*)  # convert '-abc' to '-a' '-b' '-c'
@@ -130,131 +135,178 @@ if [ "$#" != 0 ]; then
   shift # remove the EOL token
 fi
 
+if [ -n "$as_recipe" ]; then
+  if [ "$#" -ne 1 ]; then
+    error_echo "> Using recipe requires exactly 1 argument, and does not supports custom install folder."
+    exit 1
+  fi
+  # get status code and content at the same time.
+  # content="$( 2>/tmp/)"
+  export pkg="$1"
+  contentfile="$(mktemp)"
+  # we first output http_code to stderr (and actual content to stdout)
+  # Then, the 3>&2 2>&1 1>&3 swap stdout and stderr, and we redirect http status to a file.
+  http_status="$({
+    curl -Lsk -w '%{stderr}%{http_code}\n%{stdout}\n' https://raw.githubusercontent.com/soraxas/shsh-recipes/main/pkgs/"${pkg}"/latest >"$contentfile"
+   } 2>&1 )"
 
-if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
-  shsh-help install
-  exit 1
-fi
+  if [ "$http_status" = "404" ]; then
+    error_echo "> Package '$pkg' does not exists"
+    exit 1
+  fi
+  if [ "$http_status" != "200" ]; then
+    error_echo "> Error occurs when retrieving '$pkg' recipe"
+    exit 1
+  fi
 
-############################################################
+  ####### run a nested instance of `shsh` as specified by the recipe
+  # get current shell that is running this instance of `shsh``
+  current_shell="$(ps -p $$ -o 'comm=')"
+  # fallback if none is set (if for some reason)
+  [ -n "$current_shell" ] || current_shell="sh"
 
-# custom folder name
-parse_install_folder "$2" "$operation" && package="$_folder_full"
+  on_exit() {
+    status=$?
+    rm -rf "$contentfile"
+    # shellcheck disable=SC2181
+    [ "$status" -eq 0 ] && exit
+    # non-zero exit status
+    info_echo "> Error occured when executing recipe."
+  }
+  trap on_exit EXIT
 
+  SHSHRC="" "$current_shell" "$contentfile"
 
-##########################################
-if [ -n "$plain_package" ]; then
-  operation="plain"
+# ^ recipe
+#############################################
 else
-  operation="gitclone"
-fi
+#############################################
+# v normal install
 
-case "$operation" in
-  #########
-  plain)
-    if [ -z "$package" ]; then
-      # extract ref if it exists
-      ref=""
-      case "$1" in
-      */*@*)
-        IFS=@ read -r _clean_input_1 ref <<EOF
+  if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
+    shsh-help install
+    exit 1
+  fi
+
+  ############################################################
+
+  # custom folder name
+  parse_install_folder "$2" "$operation" && package="$_folder_full"
+
+  ##########################################
+  if [ -n "$plain_package" ]; then
+    operation="plain"
+  else
+    operation="gitclone"
+  fi
+
+  case "$operation" in
+    #########
+    plain)
+      if [ -z "$package" ]; then
+        # extract ref if it exists
+        ref=""
+        case "$1" in
+        */*@*)
+          IFS=@ read -r _clean_input_1 ref <<EOF
 $1
 EOF
+          ;;
+        *)
+          _clean_input_1="$1"
+          ;;
+        esac
+        ####
+        if parse_install_folder "$_clean_input_1" "$operation"; then
+          package="$_folder_full"
+        else
+          error_echo "Cannot parse folder from argunment."
+          exit 1
+        fi
+      fi
+      ;;
+    #########
+    gitclone)
+      case "${1%%@*}" in
+      */*/*)
+        IFS=/ read -r site user name <<EOF
+$1
+EOF
+        ;;
+      */*)
+        IFS=/ read -r user name <<EOF
+$1
+EOF
+        site="github.com"
         ;;
       *)
-        _clean_input_1="$1"
+        shsh-help install
+        exit 1
         ;;
       esac
-      ####
-      if parse_install_folder "$_clean_input_1" "$operation"; then
-        package="$_folder_full"
-      else
-        error_echo "Cannot parse folder from argunment."
-        exit 1
-      fi
-    fi
-    ;;
-  #########
-  gitclone)
-    case "${1%%@*}" in
-    */*/*)
-      IFS=/ read -r site user name <<EOF
-$1
-EOF
-      ;;
-    */*)
-      IFS=/ read -r user name <<EOF
-$1
-EOF
-      site="github.com"
-      ;;
-    *)
-      shsh-help install
-      exit 1
-      ;;
-    esac
-    gitrepo="${user}/${name}"
+      gitrepo="${user}/${name}"
 
-    # defaults to package's name
-    [ -z "$package" ] && package="${gitrepo%%@*}"
+      # defaults to package's name
+      [ -z "$package" ] && package="${gitrepo%%@*}"
 
-    # extract ref if it exists
-    ref=""
-    case "$gitrepo" in
-    */*@*)
-      IFS=@ read -r gitrepo ref <<EOF
+      # extract ref if it exists
+      ref=""
+      case "$gitrepo" in
+      */*@*)
+        IFS=@ read -r gitrepo ref <<EOF
 $gitrepo
 EOF
-    ;;
-  esac
-    ;;
-  #########
-  *)
-    error_echo "> Unknown error in selecting operation for parsing: '$operation'"
-    exit 1
-    ;;
-esac
-
-
-## INSTALLING
-# shellcheck disable=SC2015
-[ -n "$force_install" ] && shsh uninstall "$package" >/dev/null 2>&1 || true
-
-package_not_exists "$package" || exit 1
-
-
-on_exit() {
-  # shellcheck disable=SC2181
-  [ $? -eq 0 ] && exit
-  # non-zero exit status
-  [ -n "$no_cleanup" ] && exit
-  info_echo "> Error occured. Cleaning up..."
-  export hook_uninstall
-  shsh uninstall "$package"
-}
-trap on_exit EXIT
-
-case "$operation" in
-  plain)
-  ########################################################
-    # plain package or github-release
-    mkdir -p "${SHSH_PACKAGES_PATH}/$package"
-    ;;
-  gitclone)
-    # only perform link if clone is successful (and package not exists before)
-    if ! shsh-_clone "$use_ssh" "$site" "$gitrepo" "$ref" "$package"; then
+      ;;
+    esac
+      ;;
+    #########
+    *)
+      error_echo "> Unknown error in selecting operation for parsing: '$operation'"
       exit 1
-    fi
-    shsh-_deps "$package"
-    ;;
-  *)
-    error_echo "> Unknown error in selecting operation: '$operation'"
-    exit 1
-    ;;
-esac
+      ;;
+  esac
 
-shsh-_post-install "$package" "${SHSH_PACKAGES_PATH}/$package" "$gh_release" "$ref"
 
+  ## INSTALLING
+  # shellcheck disable=SC2015
+  [ -n "$force_install" ] && shsh uninstall "$package" >/dev/null 2>&1 || true
+
+  package_not_exists "$package" || exit 1
+
+
+  on_exit() {
+    # shellcheck disable=SC2181
+    [ $? -eq 0 ] && exit
+    # non-zero exit status
+    [ -n "$no_cleanup" ] && exit
+    info_echo "> Error occured. Cleaning up..."
+    export hook_uninstall
+    shsh uninstall "$package"
+  }
+  trap on_exit EXIT
+
+  case "$operation" in
+    plain)
+    ########################################################
+      # plain package or github-release
+      mkdir -p "${SHSH_PACKAGES_PATH}/$package"
+      ;;
+    gitclone)
+      # only perform link if clone is successful (and package not exists before)
+      if ! shsh-_clone "$use_ssh" "$site" "$gitrepo" "$ref" "$package"; then
+        exit 1
+      fi
+      shsh-_deps "$package"
+      ;;
+    *)
+      error_echo "> Unknown error in selecting operation: '$operation'"
+      exit 1
+      ;;
+  esac
+
+  shsh-_post-install "$package" "${SHSH_PACKAGES_PATH}/$package" "$gh_release" "$ref"
+
+fi
 
 [ -z "$SHSHRC" ] && exit
 ## SHSHRC
