update new flag description (wip)
Signed-off-by: Tin Lai <oscar@tinyiu.com>

diff --git a/libexec/shsh-install b/libexec/shsh-install
--- a/libexec/shsh-install
+++ b/libexec/shsh-install
@@ -1,41 +1,82 @@
 #!/usr/bin/env sh
-#
+#, respectively.
 # Summary: Installs a package from github (or a custom site)
 #
 # Usage: shsh install [--ssh] [site]/<package>[@ref] [folder] [-h|--hook <hook>]
-#
-# Hook types:
-#     [pre],[post]: Any arbitrary script that runs before and after linking, respectively.
-#     [+x]: Before linking, adds executable bit to the file given in the argunment.
-#     [a+x]: Before linking, when set, it will add executable bit to all files.
+#                     [-v|--variable <VAR>=<VAL>]
 #
 # Options:
-#       -h, --hook HOOK  add HOOK to this package, which is triggered while installing
-#                        or upgrading a package
+#       -h, --hook <HOOK_TYPE>[=<CONTENT>]
+#                    add HOOK to this package, which is triggered while 
+#                    installing or upgrading a package
+#       -v --variable <VAR>=<VAL>
+#                    set a variable VAR with value VAL,
+#                    useful for setting up files for linking 
 #
-#       --verbose        display more info for some commands
+#       --verbose    display more info for some commands
+#
+# Hook types:
+#   pre=<SCRIPT>     Any arbitrary POSIX script that runs before linking.
+#   post=<SCRIPT>    Any arbitrary POSIX script that runs after linking.
+#   uninstall=<...>  Any arbitrary POSIX script that runs before uninstalling.
+#                    For the above hooks, if multiples are given, the older
+#                    one will be overriden.
+#   +x=<FILE>        Before linking, adds executable bit to the FILE. If
+#                    multiples are given, they will be run in sequential order.
+#   a+x              Before linking, add executable bit to all files.
 # 
 # Examples:
-#   shsh install soraxas/dot-reminder  
-#                              install 'soraxas/dot-reminder' as a package
+#   shsh install soraxas/dot-reminder
+#                    install 'soraxas/dot-reminder' as a package
 #   shsh install --ssh <package>
-#                              install with ssh protocal (rather than https)
+#                    install with ssh protocal (rather than https)
+#   shsh install <package> -v FISH_COMPLETIONS=synoservice.fish:forgit.fish
+#                    link 'synoservice.fish' and 'forgit.fish' as fish
+#                    completion files
 #   shsh install <package> --hook pre="mv bin/foo bin/bar"
-#                              Execute the script "mv bin/foo bin/bar" before `shsh`
-#                              performs linking (e.g. this script renames the binary)
+#                    Execute the script "mv bin/foo bin/bar" before `shsh`
+#                    performs linking (e.g. this script renames the binary)
 #   shsh install <package> --hook +x=foobar
-#                              add a hook that add executable bits to the file 'foobar',
-#                              before linking is performed
+#                    add a hook that add executable bits to the file 'foobar',
+#                    before linking is performed
 #   shsh install <package> -h pre='make all' -h post='rm -r build/*'
-#                              add a hook that runs 'make all' to build binaries, right after
-#                              cloning and before linking is performed. Then, linking is
-#                              performed with its usual rules (i.e. all executable files in root
-#                              and in bin/). Finally, 'rm -r build/*' is ran to remove leftovers.
+#                    add a hook that runs 'make all' to build binaries, right
+#                    after cloning and before linking is performed. Then, 
+#                    linking is performed with its usual rules (i.e. all 
+#                    executable files in root and in bin/). Finally, 
+#                    'rm -r build/*' is ran to remove leftovers.
 
 
 set -e
 
 use_ssh="false"
+
+for arg; do
+  shift
+  case "$arg" in
+    --ssh)
+      use_ssh="true"
+      ;;
+    -h|--hook)
+      echo Not implemented yet
+      exit 1
+      ;;
+    -v|--variable)
+      echo Not implemented yet
+      exit 1
+      ;;
+    --)  # stop parsing
+      break
+      ;;
+    -*|--*=)
+      echo "Error: Unsupported flag '$arg'" >&2
+      exit 1
+      ;;
+    *)
+      # set back any unused args
+      set -- "$@" "$arg"
+  esac
+done
 
 # PARAMS=""
 # while (( "$#" )); do
