suport building plain package from the ground up using hooks
Signed-off-by: Tin Lai <oscar@tinyiu.com>

diff --git a/libexec/shsh-install b/libexec/shsh-install
--- a/libexec/shsh-install
+++ b/libexec/shsh-install
@@ -1,9 +1,12 @@
 #!/usr/bin/env sh
 #, respectively.
-# Summary: Installs a package from github (or a custom site)
+# Summary: Installs a package from github, custom site, or any arbitrary recipes.
 #
 # Usage: shsh install [site]/<package>[@ref] [<folder>/<folder>]
 #                     [-h|--hook <hook>] [-v|--variable <VAR>=<VAL>] [--ssh]
+#                     [--nocleanup] [-f|--force]
+#   or:  shsh install --plain <folder>/<folder>
+#                     [-h|--hook <hook>] [-v|--variable <VAR>=<VAL>]
 #                     [--nocleanup] [-f|--force]
 #
 # Options:
@@ -15,6 +18,8 @@
 #                    useful for setting up files for linking 
 #       --nocleanup  do not perform cleanup (shsh uninstall <package>)
 #                    even if something failed in the installination process
+#       --plain      do not clone from a git repository; useful to use hooks
+#                    script to build a package from the ground up
 #       -f, --force  force the installation even if the package exists
 #       --ssh        use ssh protocal instead of https
 #
@@ -52,6 +57,10 @@
 #                    linking is performed with its usual rules (i.e. all 
 #                    executable files in root and in bin/). Finally, 
 #                    'rm -r build/*' is ran to remove leftovers.
+#   shsh install --plain wsl-tools/win32yank -h pre='curl -sLo out.zip \
+#                https://<..>/releases/<..>.zip && unzip out.zip' -h +x=win32yank.exe
+#                    add a plain package by using curl to download pre-built
+#                    binary from upstream release page.
 
 
 set -e
@@ -76,6 +85,11 @@ if [ "$#" != 0 ]; then
         ;;
       -f|--force)
         force_install="true"
+        ;;
+      --plain)
+        # set a dummy remote package name
+        set -- "PLACE/HOLDER" "$@"
+        plain_package="true"
         ;;
       -h|--hook)
         case "$1" in
@@ -134,6 +148,12 @@ fi
 
 if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
   shsh-help install
+  exit 1
+fi
+
+if [ -n "$plain_package" ] && [ "$#" -lt 2 ]; then
+  shsh-help install
+  echo "Argunment <folder>/<folder> is necessary for plain package"
   exit 1
 fi
 
@@ -214,17 +234,22 @@ trap on_exit EXIT
 
 
 ## INSTALLING
-# shellcheck disable=SC2015
-[ -n "$force_install" ] && shsh uninstall "$folder" >/dev/null 2>&1 || true
-# only perform link if clone is successful (and package not exists before)
-if ! shsh-_clone "$use_ssh" "$site" "$package" "$ref" "$folder"; then
-  exit
+if [ -z "$plain_package" ]; then
+  # shellcheck disable=SC2015
+  [ -n "$force_install" ] && shsh uninstall "$folder" >/dev/null 2>&1 || true
+  # only perform link if clone is successful (and package not exists before)
+  if ! shsh-_clone "$use_ssh" "$site" "$package" "$ref" "$folder"; then
+    exit
+  fi
+  shsh-_deps "$folder"
+else
+  mkdir -p "$target_folder"
+  package="$folder"
 fi
-shsh-_deps "$folder"
 
+[ -n "$SHSH_HOOK_PRE" ] && execute_hooks "pre-hook" "$target_folder" "$SHSH_HOOK_PRE"
 [ -n "$SHSH_HOOK_PLUS_X" ] && execute_hooks "+x hook" "$target_folder" "IFS=:; for x in \$SHSH_HOOK_PLUS_X; do chmod +x \"\$x\"; done"
 [ -n "$SHSH_HOOK_ALL_PLUS_X" ] && execute_hooks "a+x hook" "$target_folder" "chmod -R +x ."
-[ -n "$SHSH_HOOK_PRE" ] && execute_hooks "pre-hook" "$target_folder" "$SHSH_HOOK_PRE"
 
 ## LINKING
 shsh-_link-bins "$folder"
